### ISSUE TITLE
cannot load pdb with parameters

### ISSUE THREAD

**Issue by interXadmin** [samirelanduk/molstar-react#2]
I am trying to load a pdb with params (like token) but it seems that the format is not recognized because it does not split the parmeters from the file name

**Comment by samirelanduk** [comment]
I'm not sure I understand - can you give an example of the code you are trying to run?

**Comment by interXadmin** [comment]
Hi 
I am trying to use molstar-react to show a pdb from url.

the url I am using e.g. is:

url = 'https://firebasestorage.googleapis.com/v0/b/pipeline-gui.appspot.com/o/6tfp.pdb?alt=media&token=32fd66d0-33c9-4f22-902f-83ac5f9a96f4?st'
passed as a prop to 

<Molstar  showControls="true" useInterface="true" url={url}  />

however I see that molstar downloads the file but does not show anything.

I see in the console that there was an error undentifying the file type and the reason is it does not separate 6tfp.pdb from the parameters so it gets .pdb?alt... as file type and throws an error.

if I put the same file on a different server with no params it works fine.

Gil

**Comment by samirelanduk** [comment]
Ah I see - ok this should be an easy fix. I'll release a new version with the fix in the next few days. Thanks for flagging.

**Comment by samirelanduk** [comment]
Should be fixed now.
