### ISSUE TITLE
Issue with stringified pdb file

### ISSUE THREAD

**Issue by sacdallago** [samirelanduk/molstar-react#4]
Hi @samirelanduk ,

thanks for the great utility :) I am trying to debug what's going wrong, but I can't seem to get to the bottom of it... I receive a PDB file from a server in string format, which I then convert to Blob and serve to the component. My react class looks like this:

```javascript
import React from "react";
import Molstar from "molstar-react";

class StructurePrediction extends React.Component {

  constructor(props) {
    super(props);

    this.state = {
      url: null,
      pdbBlob: null,
      string: null
    };
  }

  componentWillReceiveProps(newProps) {
    let data = newProps.data;
    
    let pdbBlob = new Blob([data], {
      type: "pdb",
    });

    this.setState({
      url: URL.createObjectURL(pdbBlob),
      pdbBlob: pdbBlob,
      string: data
    });
  }

  render() {
    return (
        <div id="structureViewer" style={{float: 'inherit',  width: 'inherit', height: '700px', position: 'relative'}}>
          {this.state.pdbBlob && <Molstar file={this.state.pdbBlob} useInterface={true} />}
        </div>

    );
  }
}

export default StructurePrediction;
```

While the `data` attribute passed to newProps looks something like this:
[data.txt](https://github.com/samirelanduk/molstar-react/files/9174190/data.txt) (sorry, had to put in a TXT file; was too large to post in an issue)

My console output is:

```
TypeError: Cannot read properties of undefined (reading 'entry')
    at trajectoryProps (index.js:67802:1)
    at Object.<anonymous> (index.js:67874:1)
    at step (index.js:1209:1)
    at Object.next (index.js:1189:1)
    at fulfilled (index.js:1175:1)
```

This seems to refer to the mol* base code?
![image](https://user-images.githubusercontent.com/6240943/180614640-f913a7e0-7185-4b44-81e5-baa9bedf2ab8.png)

Would really appreachiate the help :) Note that the reason why I wrapp the call into a componentWillReceiveProps is that the same instance will display multiple structures from different strings based on user input.

**Comment by samirelanduk** [comment]
The `file` object passed to the component is supposed to be an object with a `key` property and a `filestring` property. So something like `{key: "pdb", filestring: "PDB-filestring-here"}`. No conversion to blob is required.

**Comment by sacdallago** [comment]
Awesome! Thanks :)
